### ISSUE TITLE
Shopping Cart Screen

### ISSUE THREAD

**Issue by drteresavasquez** [Pencil-For-Schools/pencil-tech-ui#10]
![Image](https://github.com/user-attachments/assets/c2127a94-004b-40ed-ad80-f23d6bb02f12)

![Image](https://github.com/user-attachments/assets/fc5a3d16-f184-45ad-ba73-ba9bb1e3097f)

AC
User Select Review Order
Order Summary Page apears
Page shows item name and qty of items
User can finalize order or Go Back

Figma:https://www.figma.com/design/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?node-id=281-390&t=e4kbhL1HpzgWRNCx-4

Prototype:https://www.figma.com/proto/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?page-id=2%3A296&node-id=281-1264&node-type=SECTION&viewport=619%2C986%2C0.5&t=K687mGiCirVp7atk-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=281%3A1264

**Comment by JfBurgr** [comment]
@drteresavasquez omitted the empty cart screen. 

- As the user will be unable to edit the Order summary
- will not be able to continue to Order summary until items have been added to Cart to enable `review order` CTA
