### ISSUE TITLE
Scheduling App Reserve Input Screen 1

### ISSUE THREAD

**Issue by drteresavasquez** [Pencil-For-Schools/pencil-tech-ui#12]
![Image](https://github.com/user-attachments/assets/ac8af480-7467-4887-ab6c-683d9a008d47)

Expected
![Image](https://github.com/user-attachments/assets/bb8f6f8c-9b33-4b96-bc37-93910557830e)

AC:
User selects "Book Now" on time card
Reserve Input Screen with time card and a Teacher login input
If user selects "Cancel Time", user is redirected to schedule screen with all time options available

Prototype: https://www.figma.com/proto/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?page-id=0%3A1&node-id=181-2&node-type=CANVAS&viewport=327%2C845%2C0.25&t=xvpfEykv1Yv4X4G2-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=181%3A2&show-proto-sidebar=1

Full Figma File: https://www.figma.com/design/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?node-id=181-3&t=e4kbhL1HpzgWRNCx-4

**Comment by JfBurgr** [comment]
@drteresavasquez 
https://www.figma.com/design/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?node-id=181-3&t=NRyImS3cTGayNpiu-4
Here is the first draft of the scheduled flow. I'll break up the designs upon approval. I couldn't tag Katie's name here.

**Comment by drteresavasquez** [comment]
@JfBurgr this is excellent and u fully approve. Great work!

**Comment by kmerth** [comment]
Agree, looks thorough and Gorgeous! YAY Jeff!
