### ISSUE TITLE
Scheduling app Reserve Input 2 (if not in system)

### ISSUE THREAD

**Issue by drteresavasquez** [Pencil-For-Schools/pencil-tech-ui#13]
![Image](https://github.com/user-attachments/assets/5a079495-1f51-449d-95f7-4a0171c40288)

![Image](https://github.com/user-attachments/assets/56af0d3f-5c80-484e-822c-5dc3e3373be2)

AC:
User input credentials
Loading screen to validate credentials
If validation fails, then user is taken to Reserve Input screen 2

Prototype: https://www.figma.com/proto/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?page-id=0%3A1&node-id=181-2&node-type=CANVAS&viewport=327%2C845%2C0.25&t=xvpfEykv1Yv4X4G2-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=181%3A2&show-proto-sidebar=1

Full Figma File: https://www.figma.com/design/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?node-id=181-3&t=e4kbhL1HpzgWRNCx-4

**Comment by kmerth** [comment]
@smileycrew We updated the UI for this, so get the latest in Figma (not the attached screenshot)
Specifically the text / messages are different.
