### ISSUE TITLE
Scheduling App Confirmation Screen

### ISSUE THREAD

**Issue by drteresavasquez** [Pencil-For-Schools/pencil-tech-ui#14]
![Image](https://github.com/user-attachments/assets/870569d6-e38f-48cd-a15f-d5dca2c5d37d)

![Image](https://github.com/user-attachments/assets/a043f86a-bf98-41ae-966c-ec590d1f7f49)

AC:
User logs in or Register Information
User is taken to Confirmation screen

Prototype: https://www.figma.com/proto/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?page-id=0%3A1&node-id=181-2&node-type=CANVAS&viewport=327%2C845%2C0.25&t=xvpfEykv1Yv4X4G2-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=181%3A2&show-proto-sidebar=1

Full Figma File: https://www.figma.com/design/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?node-id=181-3&t=e4kbhL1HpzgWRNCx-4

**Comment by smileycrew** [comment]
I reused the loading code from the inventory list.
Right now there is nothing using the loading state.

The layout file will need to include the header and the background color since it is being used in all of the views.

**Comment by JfBurgr** [comment]
@smileycrew If you have time to update the "If you have any questions..."
![Image](https://github.com/user-attachments/assets/9b496c13-8b01-4e51-9942-66c2ef141957)
