### ISSUE TITLE
Shopping List Items Screen

### ISSUE THREAD

**Issue by drteresavasquez** [Pencil-For-Schools/pencil-tech-ui#9]
![Image](https://github.com/user-attachments/assets/f2a6c128-6a84-4ad0-844d-4b7a55325a9e)

![Image](https://github.com/user-attachments/assets/984aaddb-b412-4ea5-aea5-6920acbe88b9)

AC:
User Login
User is on Shopping Page
All item cards have 0 amount in the input
When user select "+" it add +1 item instead corresponding number input
When user select "-" it add -1 item instead corresponding number input
If "Max" on item card is select, number input will max limit number
If "Clear" on item card is select, number input will be O
When item is added to cart, the Review Order is clickable with total number of items added
If "Clear All" is selected all value input in the item card will be zero
If "Max All" is selected all value input in the item card will max limit number

Figma:https://www.figma.com/design/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?node-id=281-390&t=e4kbhL1HpzgWRNCx-4

Prototype:https://www.figma.com/proto/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?page-id=2%3A296&node-id=281-1264&node-type=SECTION&viewport=619%2C986%2C0.5&t=K687mGiCirVp7atk-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=281%3A1264

**Comment by JfBurgr** [comment]
@kmerth @drteresavasquez 
Please review:
Figma:https://www.figma.com/design/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?node-id=281-390&t=e4kbhL1HpzgWRNCx-4
Prototype:https://www.figma.com/proto/7ri3SEzZDogkyS4zdAocss/Team-Pencil---Hack-2024-(Mockup)?page-id=2%3A296&node-id=281-1264&node-type=SECTION&viewport=619%2C986%2C0.5&t=K687mGiCirVp7atk-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=281%3A1264
